### PR TITLE
Feature passwordless login

### PR DESCRIPTION
**Pull request by harmenjanssen**
Added passwordless login. Most of this will be merged back into Garp, but the scaffold as it is right now contains a lot of handy defaults for views and snippets for instance.

Passwordless login is made the default authentication method.

Flow's like this:

1. User submits her email address, gets redirected to a Thank You page
2. User receives an email with a login link, containing a unique token/ user_id combo
3. User clicks link and is automatically logged in.

Login links can only be used once, and only until `token_expiration_date` is reached (defaults to 30 minutes).

The diff probably contains a shitload of changes, so see me IRL for a walk-through if necessary.

### CODE REVIEW

**Comment by aapit** [comment]
Ik moet alvast vragen of je de unit test conditioneel wil maken.... :)

**Comment by harmenjanssen** [comment]
Done!

**Comment by aapit** [comment]
Niiiiice stuff!

Some feedback:
* I would like the snippets.ini addition even more if it was in English.
* Same goes for `application/modules/default/views/scripts/auth/login.phtml`
* Same goes for `application/modules/default/views/scripts/auth/tokenrequested.phtml` (maybe we need an easy way to add it in Dutch, or just take that from another project and just not use Garp_Scaffold as the base for Dutch snippets, or use `garp/application/data/i18n/nl.php`)
* garp/library/Garp/Auth/Adapter/Passwordless.php:130 contains the method `openssl_random_pseudo_bytes`, this should be enclosed by an extra 'if' to cover servers that don't have the openssl module installed. Fallback: `mt_rand()`
* `Garp_Auth_Adapter_PasswordlessTest`: can we make harmen@grrr.nl a configurable value?

**Comment by harmenjanssen** [comment]
Right on: 

- All text is in English
- Fallback for `openssl_random_pseudo_bytes` was added
- Best I can do for the email address in the testcase is making it a class constant. It's also a fictional address now.

**Comment by aapit** [comment]
Concluded that this is awesome functionality, only thing we might need to think about is how we prevent an admin login being sent to the wrong email address (typos).

**Pull request merged**
